"use strict"

var ships = [
    {
      "Name": "Aerie",
      "Class": "Medium Warship",
      "Manufacturer": "Lionheart",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "3,500,000",
      "Standard Cost": "5,567,000",
      "Shield": "5,700",
      "Hull": "1,900",
      "Combined HP": "7,600",
      "Disabled Threshold": 580,
      "% Threshold": "30.53%",
      "Sustainable Damage": "7,020",
      "Mass": 130,
      "Drag": 4.1,
      "Speed": 23.17,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.7,
      "Required Crew": 10,
      "Bunks": 28,
      "Spare Bunks": 18,
      "Max Crew": 96,
      "Cargo Space": 50,
      "Credits/Cargo": "70,000",
      "Max Cargo": 599,
      "Outfit Space": 390,
      "Credits/Outfit Space": "8,974",
      "Weapon Cap.": 150,
      "Credits/Weapon": "23,333",
      "Engine Cap.": 95,
      "Credits/Engine": "36,842",
      "Gun Ports": 2,
      "Turret Slots": 3,
      "Drone Bays": 0,
      "Fighter Bays": 2,
      "Firepower": 195
    },
    {
      "Name": "Argosy",
      "Class": "Light Freighter",
      "Manufacturer": "Southbound Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "1,960,000",
      "Standard Cost": "2,708,000",
      "Shield": "4,200",
      "Hull": "2,600",
      "Combined HP": "6,800",
      "Disabled Threshold": 712,
      "% Threshold": "27.38%",
      "Sustainable Damage": "6,088",
      "Mass": 330,
      "Drag": 5.9,
      "Speed": 13.56,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.7,
      "Required Crew": 4,
      "Bunks": 14,
      "Spare Bunks": 10,
      "Max Crew": 58,
      "Cargo Space": 120,
      "Credits/Cargo": "16,333",
      "Max Cargo": 285,
      "Outfit Space": 270,
      "Credits/Outfit Space": "7,259",
      "Weapon Cap.": 90,
      "Credits/Weapon": "21,778",
      "Engine Cap.": 80,
      "Credits/Engine": "24,500",
      "Gun Ports": 4,
      "Turret Slots": 2,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 72
    },
    {
      "Name": "Arrow",
      "Class": "Transport",
      "Manufacturer": "Syndicate",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "1,200,000",
      "Standard Cost": "3,049,000",
      "Shield": "2,000",
      "Hull": 400,
      "Combined HP": "2,400",
      "Disabled Threshold": 173,
      "% Threshold": "43.25%",
      "Sustainable Damage": "2,227",
      "Mass": 130,
      "Drag": 2.7,
      "Speed": 22.22,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.85,
      "Required Crew": 1,
      "Bunks": 5,
      "Spare Bunks": 4,
      "Max Crew": 33,
      "Cargo Space": 10,
      "Credits/Cargo": "120,000",
      "Max Cargo": 115,
      "Outfit Space": 180,
      "Credits/Outfit Space": "6,667",
      "Weapon Cap.": 50,
      "Credits/Weapon": "24,000",
      "Engine Cap.": 60,
      "Credits/Engine": "20,000",
      "Gun Ports": 2,
      "Turret Slots": 1,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 20
    },
    {
      "Name": "Auxiliary (cargo)",
      "Class": "Transport",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "13,720,000",
      "Standard Cost": "20,838,000",
      "Shield": "17,100",
      "Hull": "5,900",
      "Combined HP": "23,000",
      "Disabled Threshold": "1,187",
      "% Threshold": "20.12%",
      "Sustainable Damage": "21,813",
      "Mass": 820,
      "Drag": 13.3,
      "Speed": 15.04,
      "Fuel Capacity": 900,
      "Heat Dissipation": 0.45,
      "Required Crew": 87,
      "Bunks": 138,
      "Spare Bunks": 51,
      "Max Crew": 274,
      "Cargo Space": 450,
      "Credits/Cargo": "30,489",
      "Max Cargo": "1,254",
      "Outfit Space": 720,
      "Credits/Outfit Space": "19,056",
      "Weapon Cap.": 160,
      "Credits/Weapon": "85,750",
      "Engine Cap.": 200,
      "Credits/Engine": "68,600",
      "Gun Ports": 2,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 2,
      "Firepower": 240
    },
    {
      "Name": "Auxiliary (regular)",
      "Class": "Transport",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "13,720,000",
      "Standard Cost": "20,838,000",
      "Shield": "17,100",
      "Hull": "5,900",
      "Combined HP": "23,000",
      "Disabled Threshold": "1,187",
      "% Threshold": "20.12%",
      "Sustainable Damage": "21,813",
      "Mass": 820,
      "Drag": 13.3,
      "Speed": 15.04,
      "Fuel Capacity": 900,
      "Heat Dissipation": 0.45,
      "Required Crew": 87,
      "Bunks": 250,
      "Spare Bunks": 163,
      "Max Crew": 386,
      "Cargo Space": 250,
      "Credits/Cargo": "54,880",
      "Max Cargo": "1,054",
      "Outfit Space": 720,
      "Credits/Outfit Space": "19,056",
      "Weapon Cap.": 160,
      "Credits/Weapon": "85,750",
      "Engine Cap.": 200,
      "Credits/Engine": "68,600",
      "Gun Ports": 2,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 2,
      "Firepower": 240
    },
    {
      "Name": "Auxiliary (transport)",
      "Class": "Transport",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "13,720,000",
      "Standard Cost": "20,838,000",
      "Shield": "17,100",
      "Hull": "5,900",
      "Combined HP": "23,000",
      "Disabled Threshold": "1,187",
      "% Threshold": "20.12%",
      "Sustainable Damage": "21,813",
      "Mass": 820,
      "Drag": 13.3,
      "Speed": 15.04,
      "Fuel Capacity": 900,
      "Heat Dissipation": 0.45,
      "Required Crew": 87,
      "Bunks": 362,
      "Spare Bunks": 275,
      "Max Crew": 498,
      "Cargo Space": 50,
      "Credits/Cargo": "274,400",
      "Max Cargo": 854,
      "Outfit Space": 720,
      "Credits/Outfit Space": "19,056",
      "Weapon Cap.": 160,
      "Credits/Weapon": "85,750",
      "Engine Cap.": 200,
      "Credits/Engine": "68,600",
      "Gun Ports": 2,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 2,
      "Firepower": 240
    },
    {
      "Name": "Bactrian",
      "Class": "Heavy Warship",
      "Manufacturer": "Lionheart",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "17,600,000",
      "Standard Cost": "25,613,000",
      "Shield": "17,500",
      "Hull": "8,600",
      "Combined HP": "26,100",
      "Disabled Threshold": "1,509",
      "% Threshold": "17.55%",
      "Sustainable Damage": "24,591",
      "Mass": 940,
      "Drag": 16.1,
      "Speed": 11.18,
      "Fuel Capacity": 700,
      "Heat Dissipation": 0.4,
      "Required Crew": 70,
      "Bunks": 245,
      "Spare Bunks": 175,
      "Max Crew": 385,
      "Cargo Space": 530,
      "Credits/Cargo": "33,208",
      "Max Cargo": "1,496",
      "Outfit Space": 740,
      "Credits/Outfit Space": "23,784",
      "Weapon Cap.": 300,
      "Credits/Weapon": "58,667",
      "Engine Cap.": 180,
      "Credits/Engine": "97,778",
      "Gun Ports": 4,
      "Turret Slots": 6,
      "Drone Bays": 0,
      "Fighter Bays": 3,
      "Firepower": 705
    },
    {
      "Name": "Barb",
      "Class": "Fighter",
      "Manufacturer": "Syndicate",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "50,000",
      "Standard Cost": "258,000",
      "Shield": 800,
      "Hull": 200,
      "Combined HP": "1,000",
      "Disabled Threshold": 93,
      "% Threshold": "46.50%",
      "Sustainable Damage": 907,
      "Mass": 20,
      "Drag": 0.8,
      "Speed": 27.5,
      "Fuel Capacity": 0,
      "Heat Dissipation": 0.78,
      "Required Crew": 2,
      "Bunks": 2,
      "Spare Bunks": 0,
      "Max Crew": 10,
      "Cargo Space": 0,
      "Credits/Cargo": "",
      "Max Cargo": 45,
      "Outfit Space": 85,
      "Credits/Outfit Space": 588,
      "Weapon Cap.": 24,
      "Credits/Weapon": "2,083",
      "Engine Cap.": 22,
      "Credits/Engine": "2,273",
      "Gun Ports": 1,
      "Turret Slots": 1,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 6.6
    },
    {
      "Name": "Barb (proton)",
      "Class": "Fighter",
      "Manufacturer": "Syndicate",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "50,000",
      "Standard Cost": "305,000",
      "Shield": 800,
      "Hull": 200,
      "Combined HP": "1,000",
      "Disabled Threshold": 93,
      "% Threshold": "46.50%",
      "Sustainable Damage": 907,
      "Mass": 20,
      "Drag": 0.8,
      "Speed": 27.5,
      "Fuel Capacity": 0,
      "Heat Dissipation": 0.78,
      "Required Crew": 1,
      "Bunks": 1,
      "Spare Bunks": 0,
      "Max Crew": 9,
      "Cargo Space": 0,
      "Credits/Cargo": "",
      "Max Cargo": 45,
      "Outfit Space": 85,
      "Credits/Outfit Space": 588,
      "Weapon Cap.": 28,
      "Credits/Weapon": "1,786",
      "Engine Cap.": 22,
      "Credits/Engine": "2,273",
      "Gun Ports": 1,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 2.2
    },
    {
      "Name": "Bastion",
      "Class": "Medium Warship",
      "Manufacturer": "Southbound Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "3,860,000",
      "Standard Cost": "5,263,000",
      "Shield": "7,500",
      "Hull": "4,700",
      "Combined HP": "12,200",
      "Disabled Threshold": "1,031",
      "% Threshold": "21.94%",
      "Sustainable Damage": "11,169",
      "Mass": 580,
      "Drag": 10.3,
      "Speed": 11.65,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.5,
      "Required Crew": 17,
      "Bunks": 40,
      "Spare Bunks": 23,
      "Max Crew": 124,
      "Cargo Space": 110,
      "Credits/Cargo": "35,091",
      "Max Cargo": 425,
      "Outfit Space": 470,
      "Credits/Outfit Space": "8,213",
      "Weapon Cap.": 190,
      "Credits/Weapon": "20,316",
      "Engine Cap.": 120,
      "Credits/Engine": "32,167",
      "Gun Ports": 4,
      "Turret Slots": 3,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 190
    },
    {
      "Name": "Behemoth",
      "Class": "Heavy Freighter",
      "Manufacturer": "Betelgeuse Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "10,800,000",
      "Standard Cost": "13,324,000",
      "Shield": "7,600",
      "Hull": "6,300",
      "Combined HP": "13,900",
      "Disabled Threshold": "1,237",
      "% Threshold": "19.63%",
      "Sustainable Damage": "12,663",
      "Mass": 540,
      "Drag": 11.7,
      "Speed": 7.69,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.4,
      "Required Crew": 12,
      "Bunks": 30,
      "Spare Bunks": 18,
      "Max Crew": 122,
      "Cargo Space": 490,
      "Credits/Cargo": "22,041",
      "Max Cargo": 835,
      "Outfit Space": 510,
      "Credits/Outfit Space": "21,176",
      "Weapon Cap.": 280,
      "Credits/Weapon": "38,571",
      "Engine Cap.": 90,
      "Credits/Engine": "120,000",
      "Gun Ports": 2,
      "Turret Slots": 6,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 392
    },
    {
      "Name": "Berserker",
      "Class": "Interceptor",
      "Manufacturer": "Betelgeuse Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "520,000",
      "Standard Cost": "871,000",
      "Shield": "2,200",
      "Hull": 500,
      "Combined HP": "2,700",
      "Disabled Threshold": 210,
      "% Threshold": "42.00%",
      "Sustainable Damage": "2,490",
      "Mass": 110,
      "Drag": 2.2,
      "Speed": 29.55,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.85,
      "Required Crew": 1,
      "Bunks": 2,
      "Spare Bunks": 1,
      "Max Crew": 34,
      "Cargo Space": 10,
      "Credits/Cargo": "52,000",
      "Max Cargo": 130,
      "Outfit Space": 200,
      "Credits/Outfit Space": "2,600",
      "Weapon Cap.": 35,
      "Credits/Weapon": "14,857",
      "Engine Cap.": 65,
      "Credits/Engine": "8,000",
      "Gun Ports": 4,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 14
    },
    {
      "Name": "Blackbird",
      "Class": "Transport",
      "Manufacturer": "Tarazed",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "2,230,000",
      "Standard Cost": "3,807,000",
      "Shield": "4,400",
      "Hull": 900,
      "Combined HP": "5,300",
      "Disabled Threshold": 338,
      "% Threshold": "37.56%",
      "Sustainable Damage": "4,962",
      "Mass": 220,
      "Drag": 5,
      "Speed": 22,
      "Fuel Capacity": 700,
      "Heat Dissipation": 0.7,
      "Required Crew": 3,
      "Bunks": 28,
      "Spare Bunks": 25,
      "Max Crew": 88,
      "Cargo Space": 60,
      "Credits/Cargo": "37,167",
      "Max Cargo": 285,
      "Outfit Space": 350,
      "Credits/Outfit Space": "6,371",
      "Weapon Cap.": 90,
      "Credits/Weapon": "24,778",
      "Engine Cap.": 110,
      "Credits/Engine": "20,273",
      "Gun Ports": 0,
      "Turret Slots": 2,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 36
    },
    {
      "Name": "Bounder",
      "Class": "Transport",
      "Manufacturer": "Megaparsec",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "1,140,000",
      "Standard Cost": "1,578,000",
      "Shield": "2,200",
      "Hull": 700,
      "Combined HP": "2,900",
      "Disabled Threshold": 277,
      "% Threshold": "39.57%",
      "Sustainable Damage": "2,623",
      "Mass": 130,
      "Drag": 3.7,
      "Speed": 29.73,
      "Fuel Capacity": 900,
      "Heat Dissipation": 0.8,
      "Required Crew": 1,
      "Bunks": 17,
      "Spare Bunks": 16,
      "Max Crew": 53,
      "Cargo Space": 40,
      "Credits/Cargo": "28,500",
      "Max Cargo": 175,
      "Outfit Space": 220,
      "Credits/Outfit Space": "5,182",
      "Weapon Cap.": 50,
      "Credits/Weapon": "22,800",
      "Engine Cap.": 110,
      "Credits/Engine": "10,364",
      "Gun Ports": 0,
      "Turret Slots": 2,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 20
    },
    {
      "Name": "Boxwing",
      "Class": "Fighter",
      "Manufacturer": "Unknown",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "369,000",
      "Standard Cost": "429,000",
      "Shield": 400,
      "Hull": 800,
      "Combined HP": "1,200",
      "Disabled Threshold": 309,
      "% Threshold": "38.63%",
      "Sustainable Damage": 891,
      "Mass": 45,
      "Drag": 0.59,
      "Speed": 47.46,
      "Fuel Capacity": 0,
      "Heat Dissipation": 0.27,
      "Required Crew": 1,
      "Bunks": 1,
      "Spare Bunks": 0,
      "Max Crew": 1,
      "Cargo Space": 80,
      "Credits/Cargo": "4,613",
      "Max Cargo": 95,
      "Outfit Space": 45,
      "Credits/Outfit Space": "8,200",
      "Weapon Cap.": "",
      "Credits/Weapon": "",
      "Engine Cap.": 28,
      "Credits/Engine": "13,179",
      "Gun Ports": 0,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 0
    },
    {
      "Name": "Bulk Freighter",
      "Class": "Heavy Freighter",
      "Manufacturer": "Syndicate",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "9,400,000",
      "Standard Cost": "10,925,000",
      "Shield": "4,000",
      "Hull": "7,600",
      "Combined HP": "11,600",
      "Disabled Threshold": "1,393",
      "% Threshold": "18.33%",
      "Sustainable Damage": "10,207",
      "Mass": 870,
      "Drag": 15.8,
      "Speed": 5.38,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.5,
      "Required Crew": 6,
      "Bunks": 18,
      "Spare Bunks": 12,
      "Max Crew": 90,
      "Cargo Space": 600,
      "Credits/Cargo": "15,667",
      "Max Cargo": 870,
      "Outfit Space": 410,
      "Credits/Outfit Space": "22,927",
      "Weapon Cap.": 180,
      "Credits/Weapon": "52,222",
      "Engine Cap.": 85,
      "Credits/Engine": "110,588",
      "Gun Ports": 2,
      "Turret Slots": 5,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 216
    },
    {
      "Name": "Carrier",
      "Class": "Heavy Warship",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "15,200,000",
      "Standard Cost": "24,483,000",
      "Shield": "21,400",
      "Hull": "8,300",
      "Combined HP": "29,700",
      "Disabled Threshold": "1,475",
      "% Threshold": "17.77%",
      "Sustainable Damage": "28,225",
      "Mass": 910,
      "Drag": 17.7,
      "Speed": 11.86,
      "Fuel Capacity": 700,
      "Heat Dissipation": 0.45,
      "Required Crew": 111,
      "Bunks": 184,
      "Spare Bunks": 73,
      "Max Crew": 340,
      "Cargo Space": 100,
      "Credits/Cargo": "152,000",
      "Max Cargo": "1,273",
      "Outfit Space": 820,
      "Credits/Outfit Space": "18,537",
      "Weapon Cap.": 370,
      "Credits/Weapon": "41,081",
      "Engine Cap.": 210,
      "Credits/Engine": "72,381",
      "Gun Ports": 8,
      "Turret Slots": 4,
      "Drone Bays": 6,
      "Fighter Bays": 4,
      "Firepower": "1,406.0"
    },
    {
      "Name": "Class C Freighter",
      "Class": "Heavy Warship",
      "Manufacturer": "Syndicate",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "11,400,000",
      "Standard Cost": "14,304,000",
      "Shield": "13,500",
      "Hull": "7,600",
      "Combined HP": "21,100",
      "Disabled Threshold": "1,393",
      "% Threshold": "18.33%",
      "Sustainable Damage": "19,707",
      "Mass": 810,
      "Drag": 16.4,
      "Speed": 5.18,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.5,
      "Required Crew": 18,
      "Bunks": 43,
      "Spare Bunks": 25,
      "Max Crew": 115,
      "Cargo Space": 20,
      "Credits/Cargo": "570,000",
      "Max Cargo": 290,
      "Outfit Space": 400,
      "Credits/Outfit Space": "28,500",
      "Weapon Cap.": 140,
      "Credits/Weapon": "81,429",
      "Engine Cap.": 85,
      "Credits/Engine": "134,118",
      "Gun Ports": 0,
      "Turret Slots": 4,
      "Drone Bays": 12,
      "Fighter Bays": 0,
      "Firepower": 448
    },
    {
      "Name": "Clipper",
      "Class": "Light Freighter",
      "Manufacturer": "Southbound Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "900,000",
      "Standard Cost": "1,332,000",
      "Shield": "2,700",
      "Hull": 800,
      "Combined HP": "3,500",
      "Disabled Threshold": 309,
      "% Threshold": "38.63%",
      "Sustainable Damage": "3,191",
      "Mass": 150,
      "Drag": 3.7,
      "Speed": 21.62,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.8,
      "Required Crew": 3,
      "Bunks": 9,
      "Spare Bunks": 6,
      "Max Crew": 53,
      "Cargo Space": 70,
      "Credits/Cargo": "12,857",
      "Max Cargo": 235,
      "Outfit Space": 260,
      "Credits/Outfit Space": "3,462",
      "Weapon Cap.": 60,
      "Credits/Weapon": "15,000",
      "Engine Cap.": 80,
      "Credits/Engine": "11,250",
      "Gun Ports": 4,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 24
    },
    {
      "Name": "Combat Drone",
      "Class": "Drone",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "83,000",
      "Standard Cost": "199,000",
      "Shield": 0,
      "Hull": 700,
      "Combined HP": 700,
      "Disabled Threshold": 277,
      "% Threshold": "39.57%",
      "Sustainable Damage": 423,
      "Mass": 20,
      "Drag": 0.59,
      "Speed": 47.46,
      "Fuel Capacity": 0,
      "Heat Dissipation": 0.9,
      "Required Crew": 0,
      "Bunks": 0,
      "Spare Bunks": 0,
      "Max Crew": 2,
      "Cargo Space": 0,
      "Credits/Cargo": "",
      "Max Cargo": 30,
      "Outfit Space": 58,
      "Credits/Outfit Space": "1,431",
      "Weapon Cap.": 8,
      "Credits/Weapon": "10,375",
      "Engine Cap.": 28,
      "Credits/Engine": "2,964",
      "Gun Ports": 1,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 2.8
    },
    {
      "Name": "Container Transport",
      "Class": "Heavy Freighter",
      "Manufacturer": "Syndicate",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "9,400,000",
      "Standard Cost": "10,925,000",
      "Shield": "4,000",
      "Hull": "7,600",
      "Combined HP": "11,600",
      "Disabled Threshold": "1,393",
      "% Threshold": "18.33%",
      "Sustainable Damage": "10,207",
      "Mass": 870,
      "Drag": 15.8,
      "Speed": 5.38,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.5,
      "Required Crew": 6,
      "Bunks": 18,
      "Spare Bunks": 12,
      "Max Crew": 90,
      "Cargo Space": 600,
      "Credits/Cargo": "15,667",
      "Max Cargo": 870,
      "Outfit Space": 410,
      "Credits/Outfit Space": "22,927",
      "Weapon Cap.": 180,
      "Credits/Weapon": "52,222",
      "Engine Cap.": 85,
      "Credits/Engine": "110,588",
      "Gun Ports": 2,
      "Turret Slots": 5,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 216
    },
    {
      "Name": "Corvette",
      "Class": "Medium Warship",
      "Manufacturer": "Lionheart",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "4,400,000",
      "Standard Cost": "6,291,000",
      "Shield": "6,800",
      "Hull": 800,
      "Combined HP": "7,600",
      "Disabled Threshold": 309,
      "% Threshold": "38.63%",
      "Sustainable Damage": "7,291",
      "Mass": 150,
      "Drag": 3.5,
      "Speed": 28.57,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.7,
      "Required Crew": 8,
      "Bunks": 32,
      "Spare Bunks": 24,
      "Max Crew": 108,
      "Cargo Space": 40,
      "Credits/Cargo": "110,000",
      "Max Cargo": 325,
      "Outfit Space": 420,
      "Credits/Outfit Space": "10,476",
      "Weapon Cap.": 150,
      "Credits/Weapon": "29,333",
      "Engine Cap.": 100,
      "Credits/Engine": "44,000",
      "Gun Ports": 4,
      "Turret Slots": 2,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 120
    },
    {
      "Name": "Cruiser",
      "Class": "Heavy Warship",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "11,200,000",
      "Standard Cost": "19,793,000",
      "Shield": "19,600",
      "Hull": "6,400",
      "Combined HP": "26,000",
      "Disabled Threshold": "1,250",
      "% Threshold": "19.53%",
      "Sustainable Damage": "24,750",
      "Mass": 680,
      "Drag": 10.1,
      "Speed": 16.83,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.45,
      "Required Crew": 81,
      "Bunks": 136,
      "Spare Bunks": 55,
      "Max Crew": 280,
      "Cargo Space": 60,
      "Credits/Cargo": "186,667",
      "Max Cargo": 600,
      "Outfit Space": 760,
      "Credits/Outfit Space": "14,737",
      "Weapon Cap.": 320,
      "Credits/Weapon": "35,000",
      "Engine Cap.": 170,
      "Credits/Engine": "65,882",
      "Gun Ports": 6,
      "Turret Slots": 4,
      "Drone Bays": 4,
      "Fighter Bays": 0,
      "Firepower": 704
    },
    {
      "Name": "Dagger",
      "Class": "Fighter",
      "Manufacturer": "Lionheart",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "129,000",
      "Standard Cost": "319,000",
      "Shield": "1,000",
      "Hull": 300,
      "Combined HP": "1,300",
      "Disabled Threshold": 134,
      "% Threshold": "44.67%",
      "Sustainable Damage": "1,166",
      "Mass": 20,
      "Drag": 0.63,
      "Speed": 47.62,
      "Fuel Capacity": 0,
      "Heat Dissipation": 0.9,
      "Required Crew": 1,
      "Bunks": 1,
      "Spare Bunks": 0,
      "Max Crew": 9,
      "Cargo Space": 0,
      "Credits/Cargo": "",
      "Max Cargo": 45,
      "Outfit Space": 90,
      "Credits/Outfit Space": "1,433",
      "Weapon Cap.": 20,
      "Credits/Weapon": "6,450",
      "Engine Cap.": 30,
      "Credits/Engine": "4,300",
      "Gun Ports": 2,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 6
    },
    {
      "Name": "Dreadnought",
      "Class": "Heavy Warship",
      "Manufacturer": "Southbound Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "11,900,000",
      "Standard Cost": "18,055,000",
      "Shield": "18,100",
      "Hull": "7,300",
      "Combined HP": "25,400",
      "Disabled Threshold": "1,358",
      "% Threshold": "18.60%",
      "Sustainable Damage": "24,042",
      "Mass": 630,
      "Drag": 10.1,
      "Speed": 18.81,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.65,
      "Required Crew": 84,
      "Bunks": 147,
      "Spare Bunks": 63,
      "Max Crew": 295,
      "Cargo Space": 199,
      "Credits/Cargo": "59,799",
      "Max Cargo": 754,
      "Outfit Space": 790,
      "Credits/Outfit Space": "15,063",
      "Weapon Cap.": 360,
      "Credits/Weapon": "33,056",
      "Engine Cap.": 190,
      "Credits/Engine": "62,632",
      "Gun Ports": 4,
      "Turret Slots": 5,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 504
    },
    {
      "Name": "Dropship",
      "Class": "Fighter",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "91,000",
      "Standard Cost": "287,000",
      "Shield": 600,
      "Hull": 200,
      "Combined HP": 800,
      "Disabled Threshold": 93,
      "% Threshold": "46.50%",
      "Sustainable Damage": 707,
      "Mass": 30,
      "Drag": 0.8,
      "Speed": 50,
      "Fuel Capacity": 0,
      "Heat Dissipation": 0.9,
      "Required Crew": 1,
      "Bunks": 9,
      "Spare Bunks": 8,
      "Max Crew": 21,
      "Cargo Space": 5,
      "Credits/Cargo": "18,200",
      "Max Cargo": 65,
      "Outfit Space": 100,
      "Credits/Outfit Space": 910,
      "Weapon Cap.": 16,
      "Credits/Weapon": "5,688",
      "Engine Cap.": 40,
      "Credits/Engine": "2,275",
      "Gun Ports": 2,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 3.2
    },
    {
      "Name": "Falcon",
      "Class": "Heavy Warship",
      "Manufacturer": "Tarazed",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "10,900,000",
      "Standard Cost": "15,616,000",
      "Shield": "12,800",
      "Hull": "3,700",
      "Combined HP": "16,500",
      "Disabled Threshold": 889,
      "% Threshold": "24.03%",
      "Sustainable Damage": "15,611",
      "Mass": 510,
      "Drag": 6.7,
      "Speed": 22.39,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.7,
      "Required Crew": 52,
      "Bunks": 75,
      "Spare Bunks": 23,
      "Max Crew": 175,
      "Cargo Space": 90,
      "Credits/Cargo": "121,111",
      "Max Cargo": 465,
      "Outfit Space": 540,
      "Credits/Outfit Space": "20,185",
      "Weapon Cap.": 240,
      "Credits/Weapon": "45,417",
      "Engine Cap.": 150,
      "Credits/Engine": "72,667",
      "Gun Ports": 4,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 288
    },
    {
      "Name": "Finch",
      "Class": "Fighter",
      "Manufacturer": "Tarazed",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "126,000",
      "Standard Cost": "300,000",
      "Shield": "1,100",
      "Hull": 200,
      "Combined HP": "1,300",
      "Disabled Threshold": 93,
      "% Threshold": "46.50%",
      "Sustainable Damage": "1,207",
      "Mass": 40,
      "Drag": 0.83,
      "Speed": 48.19,
      "Fuel Capacity": 0,
      "Heat Dissipation": 0.85,
      "Required Crew": 1,
      "Bunks": 1,
      "Spare Bunks": 0,
      "Max Crew": 13,
      "Cargo Space": 0,
      "Credits/Cargo": "",
      "Max Cargo": 60,
      "Outfit Space": 110,
      "Credits/Outfit Space": "1,145",
      "Weapon Cap.": 20,
      "Credits/Weapon": "6,300",
      "Engine Cap.": 40,
      "Credits/Engine": "3,150",
      "Gun Ports": 2,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 4
    },
    {
      "Name": "Firebird",
      "Class": "Medium Warship",
      "Manufacturer": "Betelgeuse Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "3,700,000",
      "Standard Cost": "5,140,000",
      "Shield": "5,800",
      "Hull": "3,400",
      "Combined HP": "9,200",
      "Disabled Threshold": 844,
      "% Threshold": "24.82%",
      "Sustainable Damage": "8,356",
      "Mass": 290,
      "Drag": 4.5,
      "Speed": 22.22,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.6,
      "Required Crew": 7,
      "Bunks": 22,
      "Spare Bunks": 15,
      "Max Crew": 94,
      "Cargo Space": 50,
      "Credits/Cargo": "74,000",
      "Max Cargo": 320,
      "Outfit Space": 400,
      "Credits/Outfit Space": "9,250",
      "Weapon Cap.": 160,
      "Credits/Weapon": "23,125",
      "Engine Cap.": 100,
      "Credits/Engine": "37,000",
      "Gun Ports": 4,
      "Turret Slots": 2,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 128
    },
    {
      "Name": "Flivver",
      "Class": "Transport",
      "Manufacturer": "Unknown",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "180,000",
      "Standard Cost": "519,000",
      "Shield": "1,400",
      "Hull": 200,
      "Combined HP": "1,600",
      "Disabled Threshold": 93,
      "% Threshold": "46.50%",
      "Sustainable Damage": "1,507",
      "Mass": 40,
      "Drag": 1,
      "Speed": 45,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.9,
      "Required Crew": 1,
      "Bunks": 3,
      "Spare Bunks": 2,
      "Max Crew": 19,
      "Cargo Space": 5,
      "Credits/Cargo": "36,000",
      "Max Cargo": 65,
      "Outfit Space": 130,
      "Credits/Outfit Space": "1,385",
      "Weapon Cap.": 25,
      "Credits/Weapon": "7,200",
      "Engine Cap.": 45,
      "Credits/Engine": "4,000",
      "Gun Ports": 2,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 5
    },
    {
      "Name": "Freighter",
      "Class": "Light Freighter",
      "Manufacturer": "Syndicate",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "730,000",
      "Standard Cost": "1,426,000",
      "Shield": "2,000",
      "Hull": "2,000",
      "Combined HP": "4,000",
      "Disabled Threshold": 600,
      "% Threshold": "30.00%",
      "Sustainable Damage": "3,400",
      "Mass": 240,
      "Drag": 5.6,
      "Speed": 12.5,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.6,
      "Required Crew": 2,
      "Bunks": 7,
      "Spare Bunks": 5,
      "Max Crew": 47,
      "Cargo Space": 150,
      "Credits/Cargo": "4,867",
      "Max Cargo": 300,
      "Outfit Space": 250,
      "Credits/Outfit Space": "2,920",
      "Weapon Cap.": 80,
      "Credits/Weapon": "9,125",
      "Engine Cap.": 70,
      "Credits/Engine": "10,429",
      "Gun Ports": 0,
      "Turret Slots": 3,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 48
    },
    {
      "Name": "Frigate",
      "Class": "Medium Warship",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "5,200,000",
      "Standard Cost": "7,305,000",
      "Shield": "8,000",
      "Hull": "2,500",
      "Combined HP": "10,500",
      "Disabled Threshold": 694,
      "% Threshold": "27.76%",
      "Sustainable Damage": "9,806",
      "Mass": 310,
      "Drag": 5.2,
      "Speed": 19.23,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.7,
      "Required Crew": 21,
      "Bunks": 44,
      "Spare Bunks": 23,
      "Max Crew": 116,
      "Cargo Space": 35,
      "Credits/Cargo": "148,571",
      "Max Cargo": 305,
      "Outfit Space": 410,
      "Credits/Outfit Space": "12,683",
      "Weapon Cap.": 170,
      "Credits/Weapon": "30,588",
      "Engine Cap.": 100,
      "Credits/Engine": "52,000",
      "Gun Ports": 4,
      "Turret Slots": 3,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 170
    },
    {
      "Name": "Fury",
      "Class": "Interceptor",
      "Manufacturer": "Southbound Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "490,000",
      "Standard Cost": "803,000",
      "Shield": "2,000",
      "Hull": 400,
      "Combined HP": "2,400",
      "Disabled Threshold": 173,
      "% Threshold": "43.25%",
      "Sustainable Damage": "2,227",
      "Mass": 70,
      "Drag": 1.6,
      "Speed": 37.5,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.9,
      "Required Crew": 1,
      "Bunks": 3,
      "Spare Bunks": 2,
      "Max Crew": 27,
      "Cargo Space": 15,
      "Credits/Cargo": "32,667",
      "Max Cargo": 105,
      "Outfit Space": 160,
      "Credits/Outfit Space": "3,063",
      "Weapon Cap.": 40,
      "Credits/Weapon": "12,250",
      "Engine Cap.": 60,
      "Credits/Engine": "8,167",
      "Gun Ports": 4,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 16
    },
    {
      "Name": "Gunboat",
      "Class": "Light Warship",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "3,200,000",
      "Standard Cost": "4,396,000",
      "Shield": "5,800",
      "Hull": "1,400",
      "Combined HP": "7,200",
      "Disabled Threshold": 469,
      "% Threshold": "33.50%",
      "Sustainable Damage": "6,731",
      "Mass": 150,
      "Drag": 3.1,
      "Speed": 29.03,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.8,
      "Required Crew": 7,
      "Bunks": 12,
      "Spare Bunks": 5,
      "Max Crew": 56,
      "Cargo Space": 50,
      "Credits/Cargo": "64,000",
      "Max Cargo": 215,
      "Outfit Space": 270,
      "Credits/Outfit Space": "11,852",
      "Weapon Cap.": 100,
      "Credits/Weapon": "32,000",
      "Engine Cap.": 90,
      "Credits/Engine": "35,556",
      "Gun Ports": 2,
      "Turret Slots": 1,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 40
    },
    {
      "Name": "Hauler",
      "Class": "Light Freighter",
      "Manufacturer": "Unknown",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "1,430,000",
      "Standard Cost": "2,873,000",
      "Shield": "2,500",
      "Hull": "3,700",
      "Combined HP": "6,200",
      "Disabled Threshold": 889,
      "% Threshold": "24.03%",
      "Sustainable Damage": "5,311",
      "Mass": 250,
      "Drag": 10.5,
      "Speed": 7.62,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.6,
      "Required Crew": 3,
      "Bunks": 12,
      "Spare Bunks": 9,
      "Max Crew": 72,
      "Cargo Space": 130,
      "Credits/Cargo": "11,000",
      "Max Cargo": 355,
      "Outfit Space": 350,
      "Credits/Outfit Space": "4,086",
      "Weapon Cap.": 140,
      "Credits/Weapon": "10,214",
      "Engine Cap.": 80,
      "Credits/Engine": "17,875",
      "Gun Ports": 2,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 140
    },
    {
      "Name": "Hauler II",
      "Class": "Heavy Freighter",
      "Manufacturer": "Unknown",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "2,340,000",
      "Standard Cost": "3,791,000",
      "Shield": "2,900",
      "Hull": "5,200",
      "Combined HP": "8,100",
      "Disabled Threshold": "1,098",
      "% Threshold": "21.12%",
      "Sustainable Damage": "7,002",
      "Mass": 360,
      "Drag": 11.5,
      "Speed": 6.96,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.6,
      "Required Crew": 3,
      "Bunks": 12,
      "Spare Bunks": 9,
      "Max Crew": 72,
      "Cargo Space": 260,
      "Credits/Cargo": "9,000",
      "Max Cargo": 485,
      "Outfit Space": 350,
      "Credits/Outfit Space": "6,686",
      "Weapon Cap.": 140,
      "Credits/Weapon": "16,714",
      "Engine Cap.": 80,
      "Credits/Engine": "29,250",
      "Gun Ports": 2,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 140
    },
    {
      "Name": "Hauler III",
      "Class": "Heavy Freighter",
      "Manufacturer": "Unknown",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "3,260,000",
      "Standard Cost": "4,711,000",
      "Shield": "3,300",
      "Hull": "6,700",
      "Combined HP": "10,000",
      "Disabled Threshold": "1,286",
      "% Threshold": "19.19%",
      "Sustainable Damage": "8,714",
      "Mass": 470,
      "Drag": 12.5,
      "Speed": 6.4,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.6,
      "Required Crew": 3,
      "Bunks": 12,
      "Spare Bunks": 9,
      "Max Crew": 72,
      "Cargo Space": 390,
      "Credits/Cargo": "8,359",
      "Max Cargo": 615,
      "Outfit Space": 350,
      "Credits/Outfit Space": "9,314",
      "Weapon Cap.": 140,
      "Credits/Weapon": "23,286",
      "Engine Cap.": 80,
      "Credits/Engine": "40,750",
      "Gun Ports": 2,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 140
    },
    {
      "Name": "Hawk",
      "Class": "Interceptor",
      "Manufacturer": "Tarazed",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "670,000",
      "Standard Cost": "1,078,000",
      "Shield": "2,500",
      "Hull": 500,
      "Combined HP": "3,000",
      "Disabled Threshold": 210,
      "% Threshold": "42.00%",
      "Sustainable Damage": "2,790",
      "Mass": 150,
      "Drag": 2.1,
      "Speed": 33.33,
      "Fuel Capacity": 300,
      "Heat Dissipation": 0.8,
      "Required Crew": 2,
      "Bunks": 4,
      "Spare Bunks": 2,
      "Max Crew": 36,
      "Cargo Space": 20,
      "Credits/Cargo": "33,500",
      "Max Cargo": 140,
      "Outfit Space": 200,
      "Credits/Outfit Space": "3,350",
      "Weapon Cap.": 50,
      "Credits/Weapon": "13,400",
      "Engine Cap.": 70,
      "Credits/Engine": "9,571",
      "Gun Ports": 2,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 10
    },
    {
      "Name": "Headhunter",
      "Class": "Light Warship",
      "Manufacturer": "Lionheart",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "1,850,000",
      "Standard Cost": "2,676,000",
      "Shield": "3,800",
      "Hull": 700,
      "Combined HP": "4,500",
      "Disabled Threshold": 277,
      "% Threshold": "39.57%",
      "Sustainable Damage": "4,223",
      "Mass": 120,
      "Drag": 2.6,
      "Speed": 30.77,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.8,
      "Required Crew": 2,
      "Bunks": 4,
      "Spare Bunks": 2,
      "Max Crew": 44,
      "Cargo Space": 50,
      "Credits/Cargo": "37,000",
      "Max Cargo": 200,
      "Outfit Space": 250,
      "Credits/Outfit Space": "7,400",
      "Weapon Cap.": 60,
      "Credits/Weapon": "30,833",
      "Engine Cap.": 80,
      "Credits/Engine": "23,125",
      "Gun Ports": 4,
      "Turret Slots": 1,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 36
    },
    {
      "Name": "Heavy Shuttle",
      "Class": "Transport",
      "Manufacturer": "Betelgeuse Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "320,000",
      "Standard Cost": "489,000",
      "Shield": 700,
      "Hull": 700,
      "Combined HP": "1,400",
      "Disabled Threshold": 277,
      "% Threshold": "39.57%",
      "Sustainable Damage": "1,123",
      "Mass": 110,
      "Drag": 2.1,
      "Speed": 28.57,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.8,
      "Required Crew": 1,
      "Bunks": 8,
      "Spare Bunks": 7,
      "Max Crew": 24,
      "Cargo Space": 35,
      "Credits/Cargo": "9,143",
      "Max Cargo": 95,
      "Outfit Space": 120,
      "Credits/Outfit Space": "2,667",
      "Weapon Cap.": 10,
      "Credits/Weapon": "32,000",
      "Engine Cap.": 60,
      "Credits/Engine": "5,333",
      "Gun Ports": 2,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 2
    },
    {
      "Name": "Kestrel (engines)",
      "Class": "Heavy Warship",
      "Manufacturer": "Tarazed",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "14,700,000",
      "Standard Cost": "23,160,000",
      "Shield": "19,400",
      "Hull": "7,200",
      "Combined HP": "26,600",
      "Disabled Threshold": "1,346",
      "% Threshold": "18.69%",
      "Sustainable Damage": "25,254",
      "Mass": 740,
      "Drag": 10,
      "Speed": 24,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.6,
      "Required Crew": 64,
      "Bunks": 128,
      "Spare Bunks": 64,
      "Max Crew": 280,
      "Cargo Space": 120,
      "Credits/Cargo": "122,500",
      "Max Cargo": 984,
      "Outfit Space": 810,
      "Credits/Outfit Space": "18,148",
      "Weapon Cap.": 390,
      "Credits/Weapon": "37,692",
      "Engine Cap.": 240,
      "Credits/Engine": "61,250",
      "Gun Ports": 6,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 2,
      "Firepower": 741
    },
    {
      "Name": "Kestrel (shields)",
      "Class": "Heavy Warship",
      "Manufacturer": "Tarazed",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "14,700,000",
      "Standard Cost": "23,160,000",
      "Shield": "22,400",
      "Hull": "8,700",
      "Combined HP": "31,100",
      "Disabled Threshold": "1,520",
      "% Threshold": "17.47%",
      "Sustainable Damage": "29,580",
      "Mass": 740,
      "Drag": 11,
      "Speed": 19.09,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.66,
      "Required Crew": 64,
      "Bunks": 128,
      "Spare Bunks": 64,
      "Max Crew": 280,
      "Cargo Space": 120,
      "Credits/Cargo": "122,500",
      "Max Cargo": 984,
      "Outfit Space": 810,
      "Credits/Outfit Space": "18,148",
      "Weapon Cap.": 390,
      "Credits/Weapon": "37,692",
      "Engine Cap.": 210,
      "Credits/Engine": "70,000",
      "Gun Ports": 6,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 2,
      "Firepower": 741
    },
    {
      "Name": "Kestrel (weapons)",
      "Class": "Heavy Warship",
      "Manufacturer": "Tarazed",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "14,700,000",
      "Standard Cost": "23,160,000",
      "Shield": "19,400",
      "Hull": "7,200",
      "Combined HP": "26,600",
      "Disabled Threshold": "1,346",
      "% Threshold": "18.69%",
      "Sustainable Damage": "25,254",
      "Mass": 740,
      "Drag": 11,
      "Speed": 19.09,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.6,
      "Required Crew": 64,
      "Bunks": 128,
      "Spare Bunks": 64,
      "Max Crew": 280,
      "Cargo Space": 120,
      "Credits/Cargo": "122,500",
      "Max Cargo": 984,
      "Outfit Space": 810,
      "Credits/Outfit Space": "18,148",
      "Weapon Cap.": 430,
      "Credits/Weapon": "34,186",
      "Engine Cap.": 210,
      "Credits/Engine": "70,000",
      "Gun Ports": 12,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 2,
      "Firepower": "1,075.0"
    },
    {
      "Name": "Lance",
      "Class": "Fighter",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "93,000",
      "Standard Cost": "351,000",
      "Shield": 800,
      "Hull": 400,
      "Combined HP": "1,200",
      "Disabled Threshold": 173,
      "% Threshold": "43.25%",
      "Sustainable Damage": "1,027",
      "Mass": 30,
      "Drag": 0.7,
      "Speed": 42.86,
      "Fuel Capacity": 0,
      "Heat Dissipation": 0.8,
      "Required Crew": 1,
      "Bunks": 1,
      "Spare Bunks": 0,
      "Max Crew": 13,
      "Cargo Space": 0,
      "Credits/Cargo": "",
      "Max Cargo": 60,
      "Outfit Space": 100,
      "Credits/Outfit Space": 930,
      "Weapon Cap.": 20,
      "Credits/Weapon": "4,650",
      "Engine Cap.": 30,
      "Credits/Engine": "3,100",
      "Gun Ports": 2,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 4
    },
    {
      "Name": "Leviathan",
      "Class": "Heavy Warship",
      "Manufacturer": "Betelgeuse Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "9,800,000",
      "Standard Cost": "17,097,000",
      "Shield": "14,400",
      "Hull": "5,000",
      "Combined HP": "19,400",
      "Disabled Threshold": "1,071",
      "% Threshold": "21.42%",
      "Sustainable Damage": "18,329",
      "Mass": 480,
      "Drag": 7.6,
      "Speed": 15.79,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.5,
      "Required Crew": 43,
      "Bunks": 64,
      "Spare Bunks": 21,
      "Max Crew": 180,
      "Cargo Space": 80,
      "Credits/Cargo": "122,500",
      "Max Cargo": 515,
      "Outfit Space": 620,
      "Credits/Outfit Space": "15,806",
      "Weapon Cap.": 240,
      "Credits/Weapon": "40,833",
      "Engine Cap.": 120,
      "Credits/Engine": "81,667",
      "Gun Ports": 4,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 288
    },
    {
      "Name": "Manta",
      "Class": "Medium Warship",
      "Manufacturer": "Megaparsec",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "3,400,000",
      "Standard Cost": "4,905,000",
      "Shield": "5,900",
      "Hull": "1,500",
      "Combined HP": "7,400",
      "Disabled Threshold": 493,
      "% Threshold": "32.87%",
      "Sustainable Damage": "6,907",
      "Mass": 170,
      "Drag": 4.7,
      "Speed": 21.28,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.8,
      "Required Crew": 6,
      "Bunks": 10,
      "Spare Bunks": 4,
      "Max Crew": 70,
      "Cargo Space": 20,
      "Credits/Cargo": "170,000",
      "Max Cargo": 245,
      "Outfit Space": 350,
      "Credits/Outfit Space": "9,714",
      "Weapon Cap.": 140,
      "Credits/Weapon": "24,286",
      "Engine Cap.": 100,
      "Credits/Engine": "34,000",
      "Gun Ports": 6,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 84
    },
    {
      "Name": "Modified Argosy",
      "Class": "Light Warship",
      "Manufacturer": "Southbound Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "1,960,000",
      "Standard Cost": "3,336,000",
      "Shield": "4,800",
      "Hull": "1,900",
      "Combined HP": "6,700",
      "Disabled Threshold": 580,
      "% Threshold": "30.53%",
      "Sustainable Damage": "6,120",
      "Mass": 250,
      "Drag": 6.2,
      "Speed": 12.9,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.6,
      "Required Crew": 5,
      "Bunks": 12,
      "Spare Bunks": 7,
      "Max Crew": 72,
      "Cargo Space": 60,
      "Credits/Cargo": "32,667",
      "Max Cargo": 285,
      "Outfit Space": 340,
      "Credits/Outfit Space": "5,765",
      "Weapon Cap.": 140,
      "Credits/Weapon": "14,000",
      "Engine Cap.": 80,
      "Credits/Engine": "24,500",
      "Gun Ports": 4,
      "Turret Slots": 2,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 112
    },
    {
      "Name": "Mule",
      "Class": "Medium Warship",
      "Manufacturer": "Lionheart",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "4,080,000",
      "Standard Cost": "6,297,000",
      "Shield": "5,400",
      "Hull": "4,400",
      "Combined HP": "9,800",
      "Disabled Threshold": 990,
      "% Threshold": "22.50%",
      "Sustainable Damage": "8,810",
      "Mass": 320,
      "Drag": 5.7,
      "Speed": 19.3,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.5,
      "Required Crew": 14,
      "Bunks": 43,
      "Spare Bunks": 29,
      "Max Crew": 123,
      "Cargo Space": 170,
      "Credits/Cargo": "24,000",
      "Max Cargo": 617,
      "Outfit Space": 440,
      "Credits/Outfit Space": "9,273",
      "Weapon Cap.": 170,
      "Credits/Weapon": "24,000",
      "Engine Cap.": 110,
      "Credits/Engine": "37,091",
      "Gun Ports": 2,
      "Turret Slots": 5,
      "Drone Bays": 0,
      "Fighter Bays": 1,
      "Firepower": 246.5
    },
    {
      "Name": "Nest",
      "Class": "Medium Warship",
      "Manufacturer": "Southbound Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "2,500,000",
      "Standard Cost": "4,168,000",
      "Shield": "2,500",
      "Hull": "3,700",
      "Combined HP": "6,200",
      "Disabled Threshold": 889,
      "% Threshold": "24.03%",
      "Sustainable Damage": "5,311",
      "Mass": 250,
      "Drag": 10.5,
      "Speed": 7.62,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.67,
      "Required Crew": 5,
      "Bunks": 14,
      "Spare Bunks": 9,
      "Max Crew": 86,
      "Cargo Space": 40,
      "Credits/Cargo": "62,500",
      "Max Cargo": 604,
      "Outfit Space": 400,
      "Credits/Outfit Space": "6,250",
      "Weapon Cap.": 140,
      "Credits/Weapon": "17,857",
      "Engine Cap.": 80,
      "Credits/Engine": "31,250",
      "Gun Ports": 2,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 2,
      "Firepower": 210
    },
    {
      "Name": "Osprey",
      "Class": "Medium Warship",
      "Manufacturer": "Tarazed",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "4,400,000",
      "Standard Cost": "8,733,000",
      "Shield": "7,200",
      "Hull": "1,600",
      "Combined HP": "8,800",
      "Disabled Threshold": 516,
      "% Threshold": "32.25%",
      "Sustainable Damage": "8,284",
      "Mass": 270,
      "Drag": 5.9,
      "Speed": 22.03,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.8,
      "Required Crew": 9,
      "Bunks": 24,
      "Spare Bunks": 15,
      "Max Crew": 104,
      "Cargo Space": 40,
      "Credits/Cargo": "110,000",
      "Max Cargo": 340,
      "Outfit Space": 450,
      "Credits/Outfit Space": "9,778",
      "Weapon Cap.": 180,
      "Credits/Weapon": "24,444",
      "Engine Cap.": 130,
      "Credits/Engine": "33,846",
      "Gun Ports": 4,
      "Turret Slots": 2,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 144
    },
    {
      "Name": "Protector",
      "Class": "Heavy Warship",
      "Manufacturer": "Syndicate",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "5,500,000",
      "Standard Cost": "12,818,000",
      "Shield": "10,000",
      "Hull": "7,800",
      "Combined HP": "17,800",
      "Disabled Threshold": "1,417",
      "% Threshold": "18.17%",
      "Sustainable Damage": "16,383",
      "Mass": 500,
      "Drag": 10.3,
      "Speed": 9.71,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.6,
      "Required Crew": 30,
      "Bunks": 69,
      "Spare Bunks": 39,
      "Max Crew": 177,
      "Cargo Space": 50,
      "Credits/Cargo": "110,000",
      "Max Cargo": 455,
      "Outfit Space": 590,
      "Credits/Outfit Space": "9,322",
      "Weapon Cap.": 230,
      "Credits/Weapon": "23,913",
      "Engine Cap.": 100,
      "Credits/Engine": "55,000",
      "Gun Ports": 2,
      "Turret Slots": 8,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 414
    },
    {
      "Name": "Quicksilver",
      "Class": "Light Warship",
      "Manufacturer": "Megaparsec",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "1,090,000",
      "Standard Cost": "2,018,000",
      "Shield": "3,000",
      "Hull": 800,
      "Combined HP": "3,800",
      "Disabled Threshold": 309,
      "% Threshold": "38.63%",
      "Sustainable Damage": "3,491",
      "Mass": 120,
      "Drag": 2.7,
      "Speed": 25.93,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.8,
      "Required Crew": 3,
      "Bunks": 6,
      "Spare Bunks": 3,
      "Max Crew": 46,
      "Cargo Space": 10,
      "Credits/Cargo": "109,000",
      "Max Cargo": 160,
      "Outfit Space": 240,
      "Credits/Outfit Space": "4,542",
      "Weapon Cap.": 60,
      "Credits/Weapon": "18,167",
      "Engine Cap.": 70,
      "Credits/Engine": "15,571",
      "Gun Ports": 2,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 12
    },
    {
      "Name": "Rainmaker",
      "Class": "Light Warship",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "1,580,000",
      "Standard Cost": "2,281,000",
      "Shield": "3,500",
      "Hull": "1,200",
      "Combined HP": "4,700",
      "Disabled Threshold": 420,
      "% Threshold": "35.00%",
      "Sustainable Damage": "4,280",
      "Mass": 180,
      "Drag": 3.8,
      "Speed": 13.16,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.6,
      "Required Crew": 7,
      "Bunks": 14,
      "Spare Bunks": 7,
      "Max Crew": 50,
      "Cargo Space": 25,
      "Credits/Cargo": "63,200",
      "Max Cargo": 160,
      "Outfit Space": 230,
      "Credits/Outfit Space": "6,870",
      "Weapon Cap.": 60,
      "Credits/Weapon": "26,333",
      "Engine Cap.": 50,
      "Credits/Engine": "31,600",
      "Gun Ports": 6,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 36
    },
    {
      "Name": "Raven",
      "Class": "Light Warship",
      "Manufacturer": "Lionheart",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "2,200,000",
      "Standard Cost": "3,143,000",
      "Shield": "4,700",
      "Hull": "1,400",
      "Combined HP": "6,100",
      "Disabled Threshold": 469,
      "% Threshold": "33.50%",
      "Sustainable Damage": "5,631",
      "Mass": 130,
      "Drag": 3.7,
      "Speed": 27.03,
      "Fuel Capacity": 500,
      "Heat Dissipation": 0.8,
      "Required Crew": 6,
      "Bunks": 13,
      "Spare Bunks": 7,
      "Max Crew": 61,
      "Cargo Space": 30,
      "Credits/Cargo": "73,333",
      "Max Cargo": 210,
      "Outfit Space": 280,
      "Credits/Outfit Space": "7,857",
      "Weapon Cap.": 100,
      "Credits/Weapon": "22,000",
      "Engine Cap.": 100,
      "Credits/Engine": "22,000",
      "Gun Ports": 4,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 40
    },
    {
      "Name": "Roost",
      "Class": "Medium Warship",
      "Manufacturer": "Southbound Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "3,000,000",
      "Standard Cost": "4,942,000",
      "Shield": "2,900",
      "Hull": "5,200",
      "Combined HP": "8,100",
      "Disabled Threshold": "1,098",
      "% Threshold": "21.12%",
      "Sustainable Damage": "7,002",
      "Mass": 360,
      "Drag": 11.5,
      "Speed": 6.96,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.67,
      "Required Crew": 7,
      "Bunks": 16,
      "Spare Bunks": 9,
      "Max Crew": 96,
      "Cargo Space": 80,
      "Credits/Cargo": "37,500",
      "Max Cargo": 968,
      "Outfit Space": 450,
      "Credits/Outfit Space": "6,667",
      "Weapon Cap.": 140,
      "Credits/Weapon": "21,429",
      "Engine Cap.": 80,
      "Credits/Engine": "37,500",
      "Gun Ports": 2,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 4,
      "Firepower": 280
    },
    {
      "Name": "Scout",
      "Class": "Transport",
      "Manufacturer": "Lionheart",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "850,000",
      "Standard Cost": "1,284,000",
      "Shield": "1,200",
      "Hull": 400,
      "Combined HP": "1,600",
      "Disabled Threshold": 173,
      "% Threshold": "43.25%",
      "Sustainable Damage": "1,427",
      "Mass": 110,
      "Drag": 3.4,
      "Speed": 29.41,
      "Fuel Capacity": 800,
      "Heat Dissipation": 0.7,
      "Required Crew": 2,
      "Bunks": 12,
      "Spare Bunks": 10,
      "Max Crew": 48,
      "Cargo Space": 55,
      "Credits/Cargo": "15,455",
      "Max Cargo": 190,
      "Outfit Space": 220,
      "Credits/Outfit Space": "3,864",
      "Weapon Cap.": 40,
      "Credits/Weapon": "21,250",
      "Engine Cap.": 100,
      "Credits/Engine": "8,500",
      "Gun Ports": 2,
      "Turret Slots": 1,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 16
    },
    {
      "Name": "Shuttle",
      "Class": "Transport",
      "Manufacturer": "Betelgeuse Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "180,000",
      "Standard Cost": "394,000",
      "Shield": 500,
      "Hull": 600,
      "Combined HP": "1,100",
      "Disabled Threshold": 245,
      "% Threshold": "40.83%",
      "Sustainable Damage": 855,
      "Mass": 70,
      "Drag": 1.7,
      "Speed": 35.29,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.8,
      "Required Crew": 1,
      "Bunks": 6,
      "Spare Bunks": 5,
      "Max Crew": 22,
      "Cargo Space": 20,
      "Credits/Cargo": "9,000",
      "Max Cargo": 80,
      "Outfit Space": 120,
      "Credits/Outfit Space": "1,500",
      "Weapon Cap.": 10,
      "Credits/Weapon": "18,000",
      "Engine Cap.": 60,
      "Credits/Engine": "3,000",
      "Gun Ports": 1,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 1
    },
    {
      "Name": "Skein",
      "Class": "Medium Warship",
      "Manufacturer": "Southbound Shipyards",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "3,500,000",
      "Standard Cost": "5,678,000",
      "Shield": "3,300",
      "Hull": "6,700",
      "Combined HP": "10,000",
      "Disabled Threshold": "1,286",
      "% Threshold": "19.19%",
      "Sustainable Damage": "8,714",
      "Mass": 470,
      "Drag": 12.5,
      "Speed": 6.4,
      "Fuel Capacity": 700,
      "Heat Dissipation": 0.71,
      "Required Crew": 7,
      "Bunks": 18,
      "Spare Bunks": 11,
      "Max Crew": 110,
      "Cargo Space": 120,
      "Credits/Cargo": "29,167",
      "Max Cargo": "1,347",
      "Outfit Space": 500,
      "Credits/Outfit Space": "7,000",
      "Weapon Cap.": 140,
      "Credits/Weapon": "25,000",
      "Engine Cap.": 80,
      "Credits/Engine": "43,750",
      "Gun Ports": 2,
      "Turret Slots": 4,
      "Drone Bays": 0,
      "Fighter Bays": 6,
      "Firepower": 350
    },
    {
      "Name": "Sparrow",
      "Class": "Interceptor",
      "Manufacturer": "Tarazed",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "225,000",
      "Standard Cost": "448,000",
      "Shield": "1,200",
      "Hull": 300,
      "Combined HP": "1,500",
      "Disabled Threshold": 134,
      "% Threshold": "44.67%",
      "Sustainable Damage": "1,366",
      "Mass": 50,
      "Drag": 0.9,
      "Speed": 44.44,
      "Fuel Capacity": 300,
      "Heat Dissipation": 0.8,
      "Required Crew": 1,
      "Bunks": 2,
      "Spare Bunks": 1,
      "Max Crew": 18,
      "Cargo Space": 15,
      "Credits/Cargo": "15,000",
      "Max Cargo": 75,
      "Outfit Space": 130,
      "Credits/Outfit Space": "1,731",
      "Weapon Cap.": 20,
      "Credits/Weapon": "11,250",
      "Engine Cap.": 40,
      "Credits/Engine": "5,625",
      "Gun Ports": 2,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 4
    },
    {
      "Name": "Splinter",
      "Class": "Medium Warship",
      "Manufacturer": "Megaparsec",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "3,100,000",
      "Standard Cost": "4,382,000",
      "Shield": "5,200",
      "Hull": "1,700",
      "Combined HP": "6,900",
      "Disabled Threshold": 538,
      "% Threshold": "31.65%",
      "Sustainable Damage": "6,362",
      "Mass": 250,
      "Drag": 4,
      "Speed": 25,
      "Fuel Capacity": 600,
      "Heat Dissipation": 0.7,
      "Required Crew": 7,
      "Bunks": 21,
      "Spare Bunks": 14,
      "Max Crew": 93,
      "Cargo Space": 75,
      "Credits/Cargo": "41,333",
      "Max Cargo": 345,
      "Outfit Space": 400,
      "Credits/Outfit Space": "7,750",
      "Weapon Cap.": 150,
      "Credits/Weapon": "20,667",
      "Engine Cap.": 100,
      "Credits/Engine": "31,000",
      "Gun Ports": 2,
      "Turret Slots": 3,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 120
    },
    {
      "Name": "Star Barge",
      "Class": "Light Freighter",
      "Manufacturer": "Syndicate",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "190,000",
      "Standard Cost": "375,000",
      "Shield": 600,
      "Hull": "1,000",
      "Combined HP": "1,600",
      "Disabled Threshold": 367,
      "% Threshold": "36.70%",
      "Sustainable Damage": "1,233",
      "Mass": 70,
      "Drag": 2.1,
      "Speed": 19.05,
      "Fuel Capacity": 300,
      "Heat Dissipation": 0.8,
      "Required Crew": 1,
      "Bunks": 3,
      "Spare Bunks": 2,
      "Max Crew": 19,
      "Cargo Space": 50,
      "Credits/Cargo": "3,800",
      "Max Cargo": 110,
      "Outfit Space": 130,
      "Credits/Outfit Space": "1,462",
      "Weapon Cap.": 20,
      "Credits/Weapon": "9,500",
      "Engine Cap.": 40,
      "Credits/Engine": "4,750",
      "Gun Ports": 0,
      "Turret Slots": 1,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 4
    },
    {
      "Name": "Star Queen",
      "Class": "Transport",
      "Manufacturer": "Unknown",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "5,500,000",
      "Standard Cost": "7,029,000",
      "Shield": "4,100",
      "Hull": "2,200",
      "Combined HP": "6,300",
      "Disabled Threshold": 639,
      "% Threshold": "29.05%",
      "Sustainable Damage": "5,661",
      "Mass": 230,
      "Drag": 4.5,
      "Speed": 22.22,
      "Fuel Capacity": 700,
      "Heat Dissipation": 0.65,
      "Required Crew": 41,
      "Bunks": 112,
      "Spare Bunks": 71,
      "Max Crew": 176,
      "Cargo Space": 60,
      "Credits/Cargo": "91,667",
      "Max Cargo": 300,
      "Outfit Space": 360,
      "Credits/Outfit Space": "15,278",
      "Weapon Cap.": 120,
      "Credits/Weapon": "45,833",
      "Engine Cap.": 100,
      "Credits/Engine": "55,000",
      "Gun Ports": 3,
      "Turret Slots": 2,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 84
    },
    {
      "Name": "Surveillance Drone",
      "Class": "Drone",
      "Manufacturer": "Navy",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "50,000",
      "Standard Cost": "234,500",
      "Shield": 0,
      "Hull": 300,
      "Combined HP": 300,
      "Disabled Threshold": 134,
      "% Threshold": "44.67%",
      "Sustainable Damage": 166,
      "Mass": 15,
      "Drag": 0.53,
      "Speed": 52.83,
      "Fuel Capacity": 0,
      "Heat Dissipation": 0.9,
      "Required Crew": 0,
      "Bunks": 0,
      "Spare Bunks": 0,
      "Max Crew": 2,
      "Cargo Space": 0,
      "Credits/Cargo": "",
      "Max Cargo": 15,
      "Outfit Space": 53,
      "Credits/Outfit Space": 943,
      "Weapon Cap.": 0,
      "Credits/Weapon": "",
      "Engine Cap.": 28,
      "Credits/Engine": "1,786",
      "Gun Ports": 0,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 0
    },
    {
      "Name": "Vanguard",
      "Class": "Heavy Warship",
      "Manufacturer": "Syndicate",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "7,200,000",
      "Standard Cost": "13,762,000",
      "Shield": "9,800",
      "Hull": 600,
      "Combined HP": "10,400",
      "Disabled Threshold": 245,
      "% Threshold": "40.83%",
      "Sustainable Damage": "10,155",
      "Mass": 500,
      "Drag": 8,
      "Speed": 15,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.6,
      "Required Crew": 23,
      "Bunks": 45,
      "Spare Bunks": 22,
      "Max Crew": 149,
      "Cargo Space": 50,
      "Credits/Cargo": "144,000",
      "Max Cargo": 440,
      "Outfit Space": 560,
      "Credits/Outfit Space": "12,857",
      "Weapon Cap.": 220,
      "Credits/Weapon": "32,727",
      "Engine Cap.": 120,
      "Credits/Engine": "60,000",
      "Gun Ports": 7,
      "Turret Slots": 1,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 198
    },
    {
      "Name": "Wasp",
      "Class": "Interceptor",
      "Manufacturer": "Syndicate",
      "Tier": 1,
      "Faction": "Human",
      "Hull Cost": "400,000",
      "Standard Cost": "732,500",
      "Shield": "1,500",
      "Hull": 500,
      "Combined HP": "2,000",
      "Disabled Threshold": 210,
      "% Threshold": "42.00%",
      "Sustainable Damage": "1,790",
      "Mass": 60,
      "Drag": 1.2,
      "Speed": 50,
      "Fuel Capacity": 400,
      "Heat Dissipation": 0.8,
      "Required Crew": 1,
      "Bunks": 2,
      "Spare Bunks": 1,
      "Max Crew": 22,
      "Cargo Space": 10,
      "Credits/Cargo": "40,000",
      "Max Cargo": 85,
      "Outfit Space": 150,
      "Credits/Outfit Space": "2,667",
      "Weapon Cap.": 28,
      "Credits/Weapon": "14,286",
      "Engine Cap.": 60,
      "Credits/Engine": "6,667",
      "Gun Ports": 3,
      "Turret Slots": 0,
      "Drone Bays": 0,
      "Fighter Bays": 0,
      "Firepower": 8.4
    }
];
console.log(ships);

var tableHTML = "<table class = \"sortable\">" + 
                "<caption><div id = \"title\">ENDLESS SKY</div><div id = \"subtitle\">Ships</div></caption>" + 
                "<tr><th>Name</th>" +
                "<th>Class</th>" +
                "<th>Manufacturor</th>" +
                "<th>Tier</th>" +
                "<th>Faction</th>" +
                "<th>Hull Cost</th>" +
                "<th>Standard Cost</th>" +
                "<th>Shield</th>" +
                "<th>Hull</th>" +
                "<th>Combined Health</th>" +
                "<th>Disabled Threshold</th>" +
                "<th>% Threshold</th>" +
                "<th>Sustainable</th>" +
                "<th>Mass</th>" +
                "<th>Drag</th>" +
                "<th>Speed</th>" +
                "<th>Fuel Capacity</th>" +
                "<th>Heat Dissipation</th>" +
                "<th>Required Crew</th>" +
                "<th>Bunks</th>" +
                "<th>Spare Bunks</th>" +
                "<th>Max Crew</th>" +
                "<th>Cargo Space</th>" +
                "<th>Credits/Cargo</th>" +
                "<th>Max Cargo</th>" +
                "<th>Outfit Space</th>" +
                "<th>Credits/Outfit</th>" +
                "<th>Weapon Capacity</th>" +
                "<th>Credits/Weapon</th>" +
                "<th>Engine Capacity</th>" +
                "<th>Credits/Engine</th>" +
                "<th>Gun Ports</th>" +
                "<th>Turret Slots</th>" +
                "<th>Drone Bays</th>" +
                "<th>Fighter Bays</th>" +
                "<th>Firepower</th>" +
                "</tr>";

for(var i = 0; i < ships.length; i++) {
    tableHTML += "<tr><td class = \"name\">" + ships[i].Name +
                "</td><td class = \"data\">" + ships[i].Class +
                "</td><td class = \"data\">" + ships[i].Manufacturer +
                "</td><td class = \"data\">" + ships[i].Tier +
                "</td><td class = \"data\">" + ships[i].Faction +
                "</td><td class = \"data\">" + ships[i]["Hull Cost"] +
                "</td><td class = \"data\">" + ships[i]["Standard Cost"] +
                "</td><td class = \"data\">" + ships[i].Shield +
                "</td><td class = \"data\">" + ships[i].Hull +
                "</td><td class = \"data\">" + ships[i]["Combined HP"] +
                "</td><td class = \"data\">" + ships[i]["Disabled Threshold"] +
                "</td><td class = \"data\">" + ships[i]["% Threshold"] +
                "</td><td class = \"data\">" + ships[i]["Sustainable Damage"] +
                "</td><td class = \"data\">" + ships[i].Mass +
                "</td><td class = \"data\">" + ships[i].Drag +
                "</td><td class = \"data\">" + ships[i].Speed +
                "</td><td class = \"data\">" + ships[i]["Fuel Capacity"] +
                "</td><td class = \"data\">" + ships[i]["Heat Dissipation"] +
                "</td><td class = \"data\">" + ships[i]["Required Crew"] +
                "</td><td class = \"data\">" + ships[i].Bunks +
                "</td><td class = \"data\">" + ships[i]["Spare Bunks"] +
                "</td><td class = \"data\">" + ships[i]["Max Crew"] +
                "</td><td class = \"data\">" + ships[i]["Cargo Space"] +
                "</td><td class = \"data\">" + ships[i]["Credits/Cargo"] +
                "</td><td class = \"data\">" + ships[i]["Max Cargo"] +
                "</td><td class = \"data\">" + ships[i]["Outfit Space"] +
                "</td><td class = \"data\">" + ships[i]["Credits/Outfit Space"] +
                "</td><td class = \"data\">" + ships[i]["Weapon Cap."] +
                "</td><td class = \"data\">" + ships[i]["Credits/Weapon"] +
                "</td><td class = \"data\">" + ships[i]["Engine Cap."] +
                "</td><td class = \"data\">" + ships[i]["Credits/Engine"] +
                "</td><td class = \"data\">" + ships[i]["Gun Ports"] +
                "</td><td class = \"data\">" + ships[i]["Turret Slots"] +
                "</td><td class = \"data\">" + ships[i]["Drone Bays"] +
                "</td><td class = \"data\">" + ships[i]["Fighter Bays"] +
                "</td><td class = \"data\">" + ships[i].Firepower +
                "</td></tr>";
}

tableHTML += "</table>";
document.getElementById("ships").innerHTML = tableHTML;